fix the atomic number 0 issue
cosmo-epfl/librascal pull request #292
Opened 2020-09-16 16:28 UTC by felixmusil

Fix the interoperability with ASE that interpret atom symbol 'X' as atomic number 0 which was not properly handled in spherical invariants (see #288).

At the moment rascal::MaxChemElements is 130 so in principle 12 non physical atomic types are supported. I don't think it is important enough to try to make it more systematic so let's keep this as a future feature.

2020-09-17 09:24 UTC, Luthaf requested changes
The fix looks good to me, I think we should also check somewhere that all species/atomic number values we get are actually below `MaxChemElements`, to prevent silent failure if someone passes a higher value.

2020-09-17 09:28 UTC, Luthaf commented
On a more fundamental point of view, I don't understand why we are creating the keys for all possible pairs below `MaxChemElements` (https://github.com/cosmo-epfl/librascal/pull/292/files#diff-9d8839ce162b641d7825d239692b7daaR460-R461) instead of taking the pairs that actually exist in the input? The current code create 8k entries in the map, while we could get away with only ~10 if the input contains 5 species, removing a large number of allocations.

2020-09-17 09:30 UTC, Luthaf commented on src/rascal/representations/calculator_spherical_invariants.hh
>          // there are 118 atomic elements atm
Is this comment outdated? It reads like it is a leftover from when the loop was `for (int sp1{1}; sp1 < 118; sp1++)`

2020-09-17 10:37 UTC, felixmusil commented
> On a more fundamental point of view, I don't understand why we are creating the keys for all possible pairs below MaxChemElements

The main reason for this is to keep the logic 'sparcified' vs 'non sparcified' in the initialization of the class: key_map maps to different values depending on this. Also the calculators are thought as unchanging entities after initialization which would break if key_map is modified afterwards. I am not saying your remark should not be followed, just that it warrants some more discussion/thoughts.

> I think we should also check somewhere that all species/atomic number values we get are actually below MaxChemElements, to prevent silent failure if someone passes a higher value

done and tested.

2020-09-17 10:39 UTC, Luthaf approved these changes

2020-09-17 10:41 UTC, Luthaf commented
Looks good to me as a fix for the original issue =).

> The main reason for this is to keep the logic 'sparcified' vs 'non sparcified' in the initialization of the class: key_map maps to different values depending on this. Also the calculators are thought as unchanging entities after initialization which would break if key_map is modified afterwards. I am not saying your remark should not be followed, just that it warrants some more discussion/thoughts.

I think this is an unfortunate side effect of having calculator store their data inside the systems instead of managing it separately. Agreed that this should be part of a larger scale discussion

2020-09-18 09:41 UTC, rosecers requested changes
Looks good to me! Provided it passes CI I'll approve

2020-09-18 10:31 UTC, felixmusil commented
You can approve now then. The CI tests are blocking any merge with master.

2020-09-18 10:57 UTC, rosecers approved these changes

2020-09-18 12:36 UTC, merged